language: node_js
node_js:
  - "9"

before_install:
  - pyenv global 3.7

install:
  - curl https://raw.githubusercontent.com/algorand/algorand-sdk-testing/master/scripts/sdkupdate.sh -o ~/sdkupdate.sh
  - chmod +x ~/sdkupdate.sh

script:
  - npm test
  - ~/sdkupdate.sh --js
